main: net.evilblock.prisonaio.PrisonAIO
name: PrisonAIO
description: "All-in-one Prison server solution"
author: joeleoli
version: "1.0"
depend:
  - PlotSquared
  - Cubed
  - Source
  - Cosmetics
  - Vault
softdepend:
  - DeluxeTags